### ISSUE TITLE
Ambiguous fields in token program sdk

### ISSUE THREAD

**Issue by Jac0xb** [febo/pinocchio#40]
### Issue

- Lets make this consistent. Should be called `token_account` or `account`.

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/burn.rs#L20

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/burn_checked.rs#L19

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/close_account.rs#L16

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/freeze_account.rs#L16

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/initialize_account.rs#L17

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/initialize_account_2.rs#L21

https://github.com/febo/pinocchio/blob/f0eac8f192840c7e96b0890be4ec0a0d8823cfc3/programs/token/src/instructions/initialize_account_3.rs#L20

**Comment by sonicfromnewyoke** [comment]
I, personally, vote for `account`. This name should prevent misunderstandings  because this is used in the original `solana-program-library`

**Comment by febo** [comment]
> I, personally, vote for `account`. This name should prevent misunderstandings because this is used in the original `solana-program-library`

Agree.
